import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/Provider"; // Importa el Provider de Redux

const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "700"], // Puedes agregar más pesos si los necesitas
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <ReduxProvider>
          {children} {/* Redux envuelve la app aquí */}
        </ReduxProvider>
      </body>
    </html>
  );
}
